# Generated by Django 5.1.3 on 2025-04-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='promo',
            field=models.BooleanField(default=False),
        ),
    ]
